#!/usr/bin/env php
<?

require(__DIR__.'/lib/application.php');
PApplication::init();
  
class apacheDumper {
  private $db;
  public function __construct() {
    $this->db = PFactory::getDbo();
    $query = "
    CREATE TABLE IF NOT EXISTS `apache_log` (
      `id` INT(11) NOT NULL AUTO_INCREMENT,
      `ip` CHAR(15) NOT NULL DEFAULT '',
      `time` DATETIME NOT NULL,
      `uri` VARCHAR(255) NOT NULL,
      `method` ENUM('GET','POST') NOT NULL,
      `code` SMALLINT(6) NOT NULL,
      PRIMARY KEY (`id`)
    ) ENGINE=MYISAM DEFAULT CHARSET=utf8";
    $this->db->Query($query);
    }
  public function insert() {
    $handle = fopen('php://stdin', 'r');
    
    while (!feof($handle)) {
      $line = fgets($handle);
      if (empty($line)) continue;
      preg_match('/\[(.*)\]\s{1,}"(.*)"\s{1,}([0-9]{3})/Ui', $line, $matches);
      $time = $this->getDatetime($matches[1]);
      $code = addslashes($matches[3]);
      preg_match('/(GET|POST)\s{1,}(.*)\s{1,}(.*)/Ui', $matches[2], $matches);
      $method = addslashes($matches[1]);
      $uri = addslashes($matches[2]);
      preg_match('/^([0-9.]{7,15})/', $line, $matches);
      $ip = addslashes($matches[1]);
      $query = "INSERT INTO `apache_log` (`ip`, `time`, `uri`, `method`, `code`) VALUES ('$ip', '$time', '$uri', '$method', '$code')";
      $this->db->Query($query);
      }
    fclose($handle);
    }
  private static $months = array('Jan' => 1, 'Feb' => 2, 'Mar' => 3, 'Apr' => 4, 'May' => 5, 'Jun' => 6, 'Jul' => 7,
    'Aug' => 8, 'Sep' => 9, 'Oct' => 10, 'Nov' => 11, 'Dec' => 12);
  private function getDatetime($time) {
    preg_match('/([0-9]{1,})\/([a-z]{1,})\/([0-9]{4}):([0-9]{2}:[0-9]{2}:[0-9]{2})/Ui', $time, $matches);
    $day = (int)$matches[1];
    $month = (int)self::$months[$matches[2]];
    $year = (int)$matches[3];
    $time = $matches[4];
    return sprintf('%1$04d-%2$02d-%3$02d %4$s', $year, $month, $day, $time);
    }
  }
$apacheDumper = new apacheDumper();
$apacheDumper->insert();