#!/bin/bash

PROJECT=$1
OPTION=$2
cd $(dirname $(readlink -f $0))

declare -A PROFILE
declare -A SAMBA_PROFILE

source <(cat etc/projects.d/*.conf)

PROJECT_MNT_PATH=~/mnt/$PROJECT

function checkMountPoint {
  if [ -d "$PROJECT_MNT_PATH" ]; then
      mountpoint "$PROJECT_MNT_PATH"
      if [ "$?" == "0" ]; then
          echo "Project already mounted $PROJECT_MNT_PATH"
          exit 3
      else
          echo "Reconnect..."
      fi
  fi
}

function prepareMount {
  _UID=`id -u`
  _GID=`id -g`
  mkdir -p $PROJECT_MNT_PATH
}

function showStatus {
  echo ===== PROJECTS =====
  for i in "${!PROFILE[@]}"; do
    echo $i
  done
  echo
  echo ===== SAMBA PROJECTS =====
  for i in "${!SAMBA_PROFILE[@]}"; do
    echo $i
  done
  echo
  echo ===== MOUNTED =====
  mount -t fuse.sshfs
  mount -t cifs
  echo
}

CONF=`ls etc/projects.d/*.conf > /dev/null 2>&1`
if [ $? -ne "0" ]; then
    echo "No projects profiles"
    exit 2
fi

if [ -z "$PROJECT" ]; then
    showStatus
    exit 0
fi

if [ -n "${PROFILE[$PROJECT]}" ]; then
    RESP=`which sshfs`
    if [ $? -ne "0" ]; then
      echo 'No sshfs! Use: sudo apt-get install sshfs'
      exit 10
    fi
    TYPE='sshfs'
    SSH_SERVER_STR=${PROFILE[$PROJECT]}
  elif [ -n "${SAMBA_PROFILE[$PROJECT]}" ]; then
    RESP=`which mount.cifs`
    if [ $? -ne "0" ]; then
      echo 'No mount.cifs! Use: sudo apt-get install cifs-utils'
      exit 10
    fi
    TYPE='mount.cifs'
    SSH_SERVER_STR=${SAMBA_PROFILE[$PROJECT]}
  else
    echo "No such project profile"
    exit 4
fi

if [ "$TYPE" == "sshfs" ]; then

    case "$OPTION" in
        -u)
            fusermount -u -z $PROJECT_MNT_PATH
            rmdir $PROJECT_MNT_PATH
            exit 0
            ;;
        *)

            checkMountPoint

            prepareMount

            sshfs -o reconnect -o idmap=user -o uid=$_UID -o gid=$_GID -o allow_other -o default_permissions "$SSH_SERVER_STR" $PROJECT_MNT_PATH
              if [ 0 != "$?" ]; then
                echo 'Error'
                rmdir $PROJECT_MNT_PATH
                exit 5
              fi
            exit 0
            ;;
    esac

elif [ "$TYPE" == "mount.cifs" ]; then

    case "$OPTION" in

        -u)
            umount $PROJECT_MNT_PATH
            rmdir $PROJECT_MNT_PATH
            exit 0
            ;;
        *)
            checkMountPoint

            prepareMount

            /sbin/mount.cifs -o reconnect -o uid=$_UID -o gid=$_GID -o allow_other -o iocharset=utf8 ${SSH_SERVER_STR/VAR_MOUNTPOINT/$PROJECT_MNT_PATH}
            if [ 0 != "$?" ]; then
              echo 'Error'
              rmdir $PROJECT_MNT_PATH
              exit 5
            fi
            exit 0
            ;;
    esac

else

    echo "No such type"
    exit 6

fi
