#!/bin/bash

cd $(dirname $(readlink -f $0))
source config/db

ALL_PROJECTS_DIR='/var/www/apps'
dbname='dev_projects'

cd $ALL_PROJECTS_DIR
find . -maxdepth 1 -type d -print0 | while read -d $'\0' dir; do
  PROJECT_DIR=$ALL_PROJECTS_DIR$dir'/www'
  if [ -d $PROJECT_DIR ]; then
    cd $PROJECT_DIR
      P_BRANCH=`git rev-parse --abbrev-ref HEAD 2>&1`
      if [ "$?" = "0" ]; then
        P_NAME=`echo $dir | cut -d "/" -f 2`
        # shortlog=$(git --no-pager shortlog -sen) # | ~/stat/shortlog-tojson.pl)
        P_STAT=$(git log --pretty=format:"%ce" | sort | uniq -c | ~/bin/lib/tools/whodoit/shortlog-tojson.pl)
        query="CALL WDI_STATINSERT('$P_NAME', '$P_STAT')"
        mysql -s -N -u$dbuser -p$dbpass -h$dbhost $dbname -e "$query"
      fi
  fi
done